version: '3.4'

services:
  api:
    build:
      context: .
      target: DEV
      dockerfile: docker/api/Dockerfile
    container_name: '${APP_NAME}-api'
    restart: always
    depends_on:
      - database
      - redis
    volumes:
      - './app/api:/var/www'
      - '${APP_PATH_TO_DIR:-./}docker/api/conf/php.ini:/usr/local/etc/php/conf.d/user.ini'
    env_file:
      - .env

  nginx:
    build:
      context: .
      target: DEV
      dockerfile: docker/nginx/Dockerfile
    container_name: '${APP_NAME}-nginx'
    restart: always
    depends_on:
      - api
    volumes:
      - '${APP_PATH_TO_DIR:-./}docker/nginx/conf/server.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '${NGINX_PORT:-80}:80'

  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    container_name: '${APP_NAME}-dev-database'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${DB_EXTERNAL_PORT}:3306'
    volumes:
      - 'dbdata:/var/lib/mysql:delegated'
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_USER=root'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: '${APP_NAME}-redis'
    restart: always
    volumes:
      - redisdata:/bitnami/redis/data
    environment:
      - 'REDIS_HOST=${REDIS_HOST}'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
      - 'REDIS_PORT=${REDIS_PORT}'
  
  adminer:
    image: adminer:latest
    container_name: '${APP_NAME}-adminer'
    restart: always
    depends_on:
      - database
    environment:
        ADMINER_DEFAULT_DB_DRIVER: mysql
        ADMINER_DEFAULT_DB_HOST: database
        ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
        ADMINER_DEFAULT_SERVER: database
        ADMINER_DESIGN: nette
        ADMINER_PLUGINS: tables-filter tinymce
    ports:
        - "8080:8080"


volumes:
  dbdata:
  redisdata:
  state:
    driver: local